dataset: "LJSpeech"

path:
  corpus_path: "/home/guenter/projects/hal9000/ennis/voices/src/de_thorsten/24kHz/de_thorsten"
  lexicon_path: "lexicon/german_mfa.dict"
  raw_path: "./preprocessed_data/de_thorsten/wavs"
  preprocessed_path: "./preprocessed_data/de_thorsten"

preprocessing:
  val_size: 10
  text:
    language: "de"
    speaker: "de_thorsten"
    max_length: 512
  audio:
    sampling_rate: 22050
    # max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
    max_len: 1490
  pitch:
    normalization: True
  energy:
    normalization: True
