preprocessing:
  #graphemes: 'abcdefghijklmnopqrstuvwxyzäöüß0123456789-''áãåçèéêëíñóôøúûāćđğıőśşżžșțọứàʿ'
  graphemes: 'abcdefghijklmnopqrstuvwxyzäöüß0123456789-''áãåçèéêëíñóôøúûāćđğıőśşżžșțọứàʿîùăėęłš'

  #phonemes: ['ts', 'ə', 'iː', 'oː', 'pf', 'aj', 'd', 'tʃ', 'm', 'œ', 'z', 'ɛ', 'ɲ', 't', 'ɟ', 'n̩', 'b', 'ɪ', 'kʰ', 'h', 'eː', 'ɔ', 'f', 'v', 'l̩', 'n', 'x', 'yː', 'p', 'c', 'aː', 'ç', 'uː', 'ʃ', 'øː', 'a', 'l', 'j', 'ɔʏ', 'cʰ', 'aw', 'ŋ', 'ɐ', 'ʊ', 'pʰ', 'ʁ', 's', 'ʏ', 'ɡ', 'tʰ', 'k', 'm̩']
  phonemes: ["'a", "'aː", "'e", "'eː", "'i", "'iː", "'o", "'oː", "'u", "'uː", "'y", "'yː", "'æ", "'ø", "'øː", "'œ", "'ɐ", "'ɑ", "'ɑː", "'ɔ", "'ɔː", "'ə", "'ɛ", "'ɛː", "'ɜ", "'ɜː", "'ɪ", "'ʊ", "'ʌ", "'ʏ", "'ʔa", "'ʔaː", "'ʔe", "'ʔeː", "'ʔi", "'ʔiː", "'ʔo", "'ʔoː", "'ʔu", "'ʔuː", "'ʔy", "'ʔyː", "'ʔæ", "'ʔø", "'ʔøː", "'ʔœ", "'ʔɑ", "'ʔɑː", "'ʔɔ", "'ʔə", "'ʔɛ", "'ʔɛː", "'ʔɪ", "'ʔʊ", "'ʔʌ", "'ʔʏ", 'a', 'aː', 'b', 'd', 'e', 'eː', 'f', 'g', 'h', 'i', 'iː', 'j', 'k', 'l', 'm', 'n', 'o', 'oː', 'p', 'r', 's', 't', 'u', 'uː', 'v', 'w', 'x', 'y', 'yː', 'z', 'æ', 'ç', 'ð', 'ø', 'øː', 'œ', 'ɐ', 'ɑ', 'ɑː', 'ɔ', 'ɔː', 'ə', 'ɛ', 'ɛː', 'ɜ', 'ɜː', 'ɥ', 'ɪ', 'ɳ', 'ʁ', 'ʃ', 'ʊ', 'ʌ', 'ʏ', 'ʒ', 'ʔa', 'ʔaː', 'ʔe', 'ʔeː', 'ʔi', 'ʔiː', 'ʔo', 'ʔoː', 'ʔu', 'ʔuː', 'ʔy', 'ʔyː', 'ʔæ', 'ʔøː', 'ʔɐ', 'ʔɔ', 'ʔɔː', 'ʔə', 'ʔɛ', 'ʔɛː', 'ʔɪ', 'ʔʊ', 'ʔʏ', 'θ']

model:
  type: 'autoreg_transformer'        # Whether to use a forward transformer or autoregressive transformer model.
                                     # Choices: ['transformer', 'autoreg_transformer']
  d_model: 512
  d_fft: 1024
  layers: 4
  dropout: 0.1
  heads: 4
