
#   | Name             | Type           | Params
# ----------------------------------------------------
# 0 | _phoneme_encoder | PhonemeEncoder | 4.0 M 
# 1 | _gst             | GST            | 361 K 
# 2 | _mel_decoder     | MelDecoder     | 780 K 
# 3 | hifigan          | Generator      | 925 K 
# ----------------------------------------------------


model:
  emb_dim           : 128  # phoneme embedding size
  emb_reduction     : 1    # 1 -> no phoneme embedding reduction
  punct_emb_dim     : 16   # punctuation embedding size

  encoder:
    depth           : 2
    n_heads         : 2    # tiny: 1
    kernel_size     : 5    # tiny: 3
    expansion       : 2    # MixFFN expansion, tiny: 1

  decoder:
    block_depth     : 3    # tiny: 2
    n_blocks        : 3    # tiny: 2
    kernel_size     : 5

  gst:
    n_style_tokens  : 500
    n_heads         : 8
    ref_enc_filters : [32, 32, 64, 64, 128, 128]

training:
    max_epochs      : 5000
    warmup_epochs   : 25
    val_epochs      : 2

    weight_decay    : 0.00001
    lr              : 0.0001
    grad_clip       : 1.0

    batch_size      : 32
