
audio:

  sampling_rate     : 24000

  fft_size          : 2048
  fmax              : 7600
  fmin              : 80
  win_length        : 1200
  window            : hann
  num_mels          : 80
  hop_size          : 300
  filter_length     : 1200
  eps               : 1e-10
  log_base          : 10.0

model:
  max_txt_len       : 512  # characters
  max_mel_len       : 1500 # mels, 1500*300/24000 = 18.75s

  phones            : "'-abcdefghijklmnopqrstuvwxyz"
  puncts            : " ,.;:-!?\""

  emb_dim           : 512  # phoneme embedding size     medium: 512, base: 384
  emb_reduction     : 1    #                            medium:   1, base:   1
  punct_emb_dim     : 16   # punctuation embedding size medium:  16, base:  16
  dpe_emb_dim       : 32   # embedding size for _d_uration, _p_itch and _e_nergy

  encoder:

    fs2_layer              : 4
    fs2_head               : 2
    fs2_dropout            : 0.2
    vp_filter_size         : 256
    vp_kernel_size         : 3
    vp_dropout             : 0.5
    ve_n_bins              : 256

  decoder:
    kind                   : "styletts" # choices: fastspeech2, styletts

    # fastspeech2:
    n_layers               : 6
    n_head                 : 2
    conv_filter_size       : 1024
    conv_kernel_size       : [9, 1]
    dropout                : 0.2
    scln                   : true

    # styletts:

  resnet:
    layers          : [3, 4, 6, 3]
    num_filters     : [32, 64, 128, 256]
    encoder_type    : "ASP" # "ASP" or "SAP"

training:
    weight_decay    : 0.0         # was: 0.00001
    betas           : [0.0, 0.99] # was: [0.0, 0.999]
    eps             : 0.000000001 # 1e-9, default: 1e-8
    grad_clip       : 1.0
