dataset: "LJSpeech"

path:
  corpus_path: "/home/guenter/projects/hal9000/ennis/voices/src/cv-corpus-17.0-2024-03-15/de_speakers_lj_100_enh/speaker_84"
  lexicon_path: "lexicon/german_mfa.dict"
  raw_path: "./preprocessed_data/de_cv_speaker_84/wavs"
  preprocessed_path: "./preprocessed_data/de_cv_speaker_84"

preprocessing:
  val_size: 10
  text:
    language: "de"
    speaker: "de_cv_speaker_84"
    max_length: 512
  audio:
    sampling_rate: 22050
    # max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    normalization: True
  energy:
    normalization: True
